server {
    listen 443 ssl;
    http2 on;
    server_name faroise.online www.faroise.online;

    ssl_certificate     /etc/letsencrypt/live/faroise.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/faroise.online/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    root /var/www/public;
    index index.php;
    client_max_body_size 30M;

    location ^~ /storage/ {
        alias /var/www/storage/app/public/;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 60;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff|ttf|mp3|ogg|wav|aac)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
